import { AppSidebar } from '@/components/app-sidebar'
import { SiteHeader } from '@/components/site-header'
import { ThemeModeProvider } from '@/components/theme-mode-provider'
import { ThemeProvider } from '@/components/theme-provider'
import { SidebarInset, SidebarProvider } from '@/components/ui/sidebar'
import { requireAuth } from '@/lib/auth/session'
import { getQueryClient, trpc } from '@/lib/trpc/server'
import { ReactQueryDevtools } from '@tanstack/react-query-devtools'
import { dehydrate, HydrationBoundary } from '@tanstack/react-query'
import { Metadata } from 'next'

export const metadata: Metadata = {
  title: 'Blog Admin',
  description: 'Generated by create next app'
}

export default async function AdminLayout({
  children
}: {
  children: React.ReactNode
}) {
  await requireAuth()

  const queryClient = getQueryClient()
  const theme = await queryClient.fetchQuery(trpc.admin.theme.get.queryOptions())
  const currentTheme = theme.id

  return (
    <HydrationBoundary state={dehydrate(queryClient)}>
      <div className="bg-sidebar">
        <ReactQueryDevtools />
        <ThemeModeProvider>
          <ThemeProvider themeId={currentTheme} />
          <SidebarProvider
            style={
              {
                '--sidebar-width': 'calc(var(--spacing) * 72)',
                '--header-height': 'calc(var(--spacing) * 12)'
              } as React.CSSProperties
            }
          >
            <AppSidebar variant="inset" />
            <SidebarInset>
              <SiteHeader />
              <div className="flex flex-1 flex-col">
                <div className="@container/main flex flex-1 flex-col gap-2 p-4">
                  {children}
                </div>
              </div>
            </SidebarInset>
          </SidebarProvider>
        </ThemeModeProvider>
      </div>
    </HydrationBoundary>
  )
}
